#!/bin/sh

FILE="/usr/share/luci/menu.d/luci-mod-system.json"

if [ -f "$FILE" ]; then
    # Tworzymy kopię zapasową pliku
    cp "$FILE" "${FILE}.bak"

    # Usuwamy linię z kluczem, kolejne 10 linii bloku oraz 1 pustą linię pod spodem (+11 linii łącznie)
    sed -i '/"admin\/system\/plugins": {/,+11d' "$FILE"

    # Czyszczenie pamięci podręcznej LuCI
    rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
fi

exit 0
